/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#include "CoreNProtocol.h"

static asn_TYPE_member_t asn_MBR_CoreNProtocol_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CoreNProtocol, choice.setsvcname),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SetSvcName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"setsvcname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoreNProtocol, choice.svcsann),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SvcAnnounce,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"svcsann"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoreNProtocol, choice.errormsg),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoreNError,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"errormsg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoreNProtocol, choice.info_request),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoreNInfoRequest,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"info-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoreNProtocol, choice.info_response),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoreNInfoResponse,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"info-response"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_CoreNProtocol_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* setsvcname */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* svcsann */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* errormsg */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* info-request */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* info-response */
};
static asn_CHOICE_specifics_t asn_SPC_CoreNProtocol_specs_1 = {
	sizeof(struct CoreNProtocol),
	offsetof(struct CoreNProtocol, _asn_ctx),
	offsetof(struct CoreNProtocol, present),
	sizeof(((struct CoreNProtocol *)0)->present),
	asn_MAP_CoreNProtocol_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CoreNProtocol = {
	"CoreNProtocol",
	"CoreNProtocol",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CoreNProtocol_1,
	5,	/* Elements count */
	&asn_SPC_CoreNProtocol_specs_1	/* Additional specs */
};

