/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_CoreNInfoCode_H_
#define	_CoreNInfoCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CoreNInfoCode {
	CoreNInfoCode_router_table	= 0,
	CoreNInfoCode_nodes	= 1,
	CoreNInfoCode_count_of_session	= 2,
	CoreNInfoCode_clients	= 3
} e_CoreNInfoCode;

/* CoreNInfoCode */
typedef ENUMERATED_t	 CoreNInfoCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoreNInfoCode;
asn_struct_free_f CoreNInfoCode_free;
asn_struct_print_f CoreNInfoCode_print;
asn_constr_check_f CoreNInfoCode_constraint;
ber_type_decoder_f CoreNInfoCode_decode_ber;
der_type_encoder_f CoreNInfoCode_encode_der;
xer_type_decoder_f CoreNInfoCode_decode_xer;
xer_type_encoder_f CoreNInfoCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CoreNInfoCode_H_ */
#include <asn_internal.h>
