/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_CoreNInfoResponse_H_
#define	_CoreNInfoResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "CoreNInfoCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CoreNInfoResponse */
typedef struct CoreNInfoResponse {
	UTF8String_t	 info;
	CoreNInfoCode_t	 code;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoreNInfoResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoreNInfoResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _CoreNInfoResponse_H_ */
#include <asn_internal.h>
