/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_CoreNErrorCode_H_
#define	_CoreNErrorCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CoreNErrorCode {
	CoreNErrorCode_success	= 0,
	CoreNErrorCode_unknown_error	= 1,
	CoreNErrorCode_coren_svc_node_not_found	= 2,
	CoreNErrorCode_svc_not_found	= 3,
	CoreNErrorCode_svc_and_or_conn_not_found	= 4,
	CoreNErrorCode_coren_svc_message_is_empty	= 5,
	CoreNErrorCode_coren_svc_body_constrait_validation_failed	= 6,
	CoreNErrorCode_coren_svc_body_decode_message_failed	= 7,
	CoreNErrorCode_coren_svc_reg_host_src_is_incorrect	= 8,
	CoreNErrorCode_session_flags_arent_correct	= 9,
	CoreNErrorCode_session_already_exists	= 10,
	CoreNErrorCode_session_not_found	= 11,
	CoreNErrorCode_session_addresses_is_incorrect	= 12,
	CoreNErrorCode_session_closed_is_mandatory	= 13,
	CoreNErrorCode_session_timeout	= 14
} e_CoreNErrorCode;

/* CoreNErrorCode */
typedef ENUMERATED_t	 CoreNErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoreNErrorCode;
asn_struct_free_f CoreNErrorCode_free;
asn_struct_print_f CoreNErrorCode_print;
asn_constr_check_f CoreNErrorCode_constraint;
ber_type_decoder_f CoreNErrorCode_decode_ber;
der_type_encoder_f CoreNErrorCode_encode_der;
xer_type_decoder_f CoreNErrorCode_decode_xer;
xer_type_encoder_f CoreNErrorCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CoreNErrorCode_H_ */
#include <asn_internal.h>
