/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_CoreNProtocol_H_
#define	_CoreNProtocol_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SetSvcName.h"
#include "SvcAnnounce.h"
#include "CoreNError.h"
#include "CoreNInfoRequest.h"
#include "CoreNInfoResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CoreNProtocol_PR {
	CoreNProtocol_PR_NOTHING,	/* No components present */
	CoreNProtocol_PR_setsvcname,
	CoreNProtocol_PR_svcsann,
	CoreNProtocol_PR_errormsg,
	CoreNProtocol_PR_info_request,
	CoreNProtocol_PR_info_response
} CoreNProtocol_PR;

/* CoreNProtocol */
typedef struct CoreNProtocol {
	CoreNProtocol_PR present;
	union CoreNProtocol_u {
		SetSvcName_t	 setsvcname;
		SvcAnnounce_t	 svcsann;
		CoreNError_t	 errormsg;
		CoreNInfoRequest_t	 info_request;
		CoreNInfoResponse_t	 info_response;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoreNProtocol_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoreNProtocol;

#ifdef __cplusplus
}
#endif

#endif	/* _CoreNProtocol_H_ */
#include <asn_internal.h>
