/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_CoreNError_H_
#define	_CoreNError_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CoreNErrorCode.h"
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CoreNError */
typedef struct CoreNError {
	CoreNErrorCode_t	 errorcode;
	UTF8String_t	*errormsg	/* OPTIONAL */;
	UTF8String_t	 sid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoreNError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoreNError;

#ifdef __cplusplus
}
#endif

#endif	/* _CoreNError_H_ */
#include <asn_internal.h>
