/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_Message_H_
#define	_Message_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgAddr.h"
#include <INTEGER.h>
#include <UTF8String.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Message */
typedef struct Message {
	MsgAddr_t	 src;
	MsgAddr_t	 dst;
	INTEGER_t	 flags;
	UTF8String_t	*sid	/* OPTIONAL */;
	INTEGER_t	*tmo	/* OPTIONAL */;
	UTF8String_t	*label	/* OPTIONAL */;
	OCTET_STRING_t	*body	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Message_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Message;

#ifdef __cplusplus
}
#endif

#endif	/* _Message_H_ */
#include <asn_internal.h>
