/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#include "MsgAddr.h"

static asn_TYPE_member_t asn_MBR_MsgAddr_1[] = {
	{ ATF_POINTER, 3, offsetof(struct MsgAddr, hostname),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hostname"
		},
	{ ATF_POINTER, 2, offsetof(struct MsgAddr, svcname),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"svcname"
		},
	{ ATF_POINTER, 1, offsetof(struct MsgAddr, svcconn),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"svcconn"
		},
};
static const ber_tlv_tag_t asn_DEF_MsgAddr_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MsgAddr_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* hostname */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* svcname */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* svcconn */
};
static asn_SEQUENCE_specifics_t asn_SPC_MsgAddr_specs_1 = {
	sizeof(struct MsgAddr),
	offsetof(struct MsgAddr, _asn_ctx),
	asn_MAP_MsgAddr_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MsgAddr = {
	"MsgAddr",
	"MsgAddr",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MsgAddr_tags_1,
	sizeof(asn_DEF_MsgAddr_tags_1)
		/sizeof(asn_DEF_MsgAddr_tags_1[0]), /* 1 */
	asn_DEF_MsgAddr_tags_1,	/* Same as above */
	sizeof(asn_DEF_MsgAddr_tags_1)
		/sizeof(asn_DEF_MsgAddr_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MsgAddr_1,
	3,	/* Elements count */
	&asn_SPC_MsgAddr_specs_1	/* Additional specs */
};

