/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MsgProto1"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/coren_cpp/protocol/coren.asn1"
 * 	`asn1c -fwide-types`
 */

#include "SvcAnnounce.h"

static asn_TYPE_member_t asn_MBR_data_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AnnounceData,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_data_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_data_specs_4 = {
	sizeof(struct data),
	offsetof(struct data, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_data_4 = {
	"data",
	"data",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_data_tags_4,
	sizeof(asn_DEF_data_tags_4)
		/sizeof(asn_DEF_data_tags_4[0]) - 1, /* 1 */
	asn_DEF_data_tags_4,	/* Same as above */
	sizeof(asn_DEF_data_tags_4)
		/sizeof(asn_DEF_data_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_data_4,
	1,	/* Single element */
	&asn_SPC_data_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SvcAnnounce_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SvcAnnounce, announce_timeout),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"announce-timeout"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SvcAnnounce, hostname),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hostname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SvcAnnounce, data),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_data_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
};
static const ber_tlv_tag_t asn_DEF_SvcAnnounce_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SvcAnnounce_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* announce-timeout */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hostname */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* data */
};
static asn_SEQUENCE_specifics_t asn_SPC_SvcAnnounce_specs_1 = {
	sizeof(struct SvcAnnounce),
	offsetof(struct SvcAnnounce, _asn_ctx),
	asn_MAP_SvcAnnounce_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SvcAnnounce = {
	"SvcAnnounce",
	"SvcAnnounce",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SvcAnnounce_tags_1,
	sizeof(asn_DEF_SvcAnnounce_tags_1)
		/sizeof(asn_DEF_SvcAnnounce_tags_1[0]), /* 1 */
	asn_DEF_SvcAnnounce_tags_1,	/* Same as above */
	sizeof(asn_DEF_SvcAnnounce_tags_1)
		/sizeof(asn_DEF_SvcAnnounce_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SvcAnnounce_1,
	3,	/* Elements count */
	&asn_SPC_SvcAnnounce_specs_1	/* Additional specs */
};

