/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CnoraProtocol"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/cnora_cpp/protocol/cnora.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_DbResponse_H_
#define	_DbResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DbRows;
struct DbValues;

/* DbResponse */
typedef struct DbResponse {
	INTEGER_t	 code;
	UTF8String_t	*message	/* OPTIONAL */;
	struct DbRows	*dataset	/* OPTIONAL */;
	struct DbValues	*params	/* OPTIONAL */;
	UTF8String_t	*label	/* OPTIONAL */;
	INTEGER_t	*total_rows_num	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DbResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DbResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DbRows.h"
#include "DbValues.h"

#endif	/* _DbResponse_H_ */
#include <asn_internal.h>
