/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CnoraProtocol"
 * 	found in "/opt/svyazcom/ss7_dmp_cnora/ss7_dmp/cnora_cpp/protocol/cnora.asn1"
 * 	`asn1c -fwide-types`
 */

#ifndef	_DbValue_H_
#define	_DbValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <INTEGER.h>
#include <UTF8String.h>
#include <REAL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DbValue_PR {
	DbValue_PR_NOTHING,	/* No components present */
	DbValue_PR_null,
	DbValue_PR_integer,
	DbValue_PR_string,
	DbValue_PR_number
} DbValue_PR;

/* DbValue */
typedef struct DbValue {
	DbValue_PR present;
	union DbValue_u {
		NULL_t	 null;
		INTEGER_t	 integer;
		UTF8String_t	 string;
		REAL_t	 number;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DbValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DbValue;

#ifdef __cplusplus
}
#endif

#endif	/* _DbValue_H_ */
#include <asn_internal.h>
